config/routes.rb
Rails.application.routes.draw do
  resources :user_recipes, only: [:index]
  resources :ingredients
  resources :recipes, only: [:index, :create, :destroy]
  # custom url for recipe summary
  get '/recipe/summary', to:'recipes#summary'
  resources :users, only: [:index, :show, :update, :destroy, :create]
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_recipe.rb
class UserRecipe < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
    has_many :ingredients
end

app/controllers/user_recipes_controller.rb
class UserRecipesController < ApplicationController
  before_action :set_user_recipe, only: %i[ show edit update destroy ]

  # GET /user_recipes or /user_recipes.json
  def index
    user_recipes = UserRecipe.all
    render json: user_recipes, each_serializer: UserRecipeSerializer
  end

  # # GET /user_recipes/1 or /user_recipes/1.json
  # def show
  # end

  # # GET /user_recipes/new
  # def new
  #   @user_recipe = UserRecipe.new
  # end

  # # GET /user_recipes/1/edit
  # def edit
  # end

  # # POST /user_recipes or /user_recipes.json
  # def create
  #   @user_recipe = UserRecipe.new(user_recipe_params)

  #   respond_to do |format|
  #     if @user_recipe.save
  #       format.html { redirect_to user_recipe_url(@user_recipe), notice: "User recipe was successfully created." }
  #       format.json { render :show, status: :created, location: @user_recipe }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /user_recipes/1 or /user_recipes/1.json
  # def update
  #   respond_to do |format|
  #     if @user_recipe.update(user_recipe_params)
  #       format.html { redirect_to user_recipe_url(@user_recipe), notice: "User recipe was successfully updated." }
  #       format.json { render :show, status: :ok, location: @user_recipe }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /user_recipes/1 or /user_recipes/1.json
  # def destroy
  #   @user_recipe.destroy

  #   respond_to do |format|
  #     format.html { redirect_to user_recipes_url, notice: "User recipe was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user_recipe
  #     @user_recipe = UserRecipe.find(params[:id])
  #   end

    # # Only allow a list of trusted parameters through.
    # def user_recipe_params
    #   params.fetch(:user_recipe, {})
    # end
end

app/helpers/user_recipes_helper.rb
module UserRecipesHelper
end

app/views/user_recipes/_form.html.erb
<%= form_with(model: user_recipe) do |form| %>
  <% if user_recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_recipe.errors.count, "error") %> prohibited this user_recipe from being saved:</h2>

      <ul>
        <% user_recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_recipes/_user_recipe.html.erb
<div id="<%= dom_id user_recipe %>">
</div>

app/views/user_recipes/edit.html.erb
<h1>Editing user recipe</h1>

<%= render "form", user_recipe: @user_recipe %>

<br>

<div>
  <%= link_to "Show this user recipe", @user_recipe %> |
  <%= link_to "Back to user recipes", user_recipes_path %>
</div>

app/views/user_recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User recipes</h1>

<div id="user_recipes">
  <% @user_recipes.each do |user_recipe| %>
    <%= render user_recipe %>
    <p>
      <%= link_to "Show this user recipe", user_recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New user recipe", new_user_recipe_path %>

app/views/user_recipes/new.html.erb
<h1>New user recipe</h1>

<%= render "form", user_recipe: @user_recipe %>

<br>

<div>
  <%= link_to "Back to user recipes", user_recipes_path %>
</div>

app/views/user_recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_recipe %>

<div>
  <%= link_to "Edit this user recipe", edit_user_recipe_path(@user_recipe) %> |
  <%= link_to "Back to user recipes", user_recipes_path %>

  <%= button_to "Destroy this user recipe", @user_recipe, method: :delete %>
</div>